#!/bin/bash

mkdir -p stream
ffmpeg \
	-re \
	-stream_loop -1 \
	-i earth.mp4 \
	-codec:v libx264 \
	-profile:v baseline \
	-pix_fmt yuv420p \
	-level 4 \
	-preset veryfast \
	-codec:a aac \
	-f dash \
	-window_size 5 \
	-remove_at_exit 1 \
	stream/live.mpd
